### ISSUE TITLE
前端无法获取mock数据（严重）

### ISSUE THREAD

**Issue by Nayacco** [diwand/YapiIdeaUploadPlugin#11]
## 版本号
~ 1.6.7

## 什么问题
~可能是类型的原因，导致前端无法获取mock数据

![image](https://user-images.githubusercontent.com/22909744/58454214-4e262400-8150-11e9-8f63-f5d4acefa198.png)

![image](https://user-images.githubusercontent.com/22909744/58454248-74e45a80-8150-11e9-94b1-3fa9f75c7335.png)

前端并没有long类型，或者enum类型，手动从yapi页面上修改类型后，数组依然不返回值（ps：已经设置了数组最小个数）

**Comment by Nayacco** [comment]
其他非生成的接口也受到了影响，数组都无法生成mock数据

**Comment by vinsoncho** [comment]
![image](https://user-images.githubusercontent.com/22909744/58461304-eed10f80-8161-11e9-923a-4727ac056c4c.png)

比对了数据，应该是这个字段产生的影响

**Comment by qbb-dev** [comment]
应该和long 类型没有关系，请提供下接口定义，我这边复现不了

**Comment by Nayacco** [comment]
部署新环境测试了一下，是yapi的bug，必须给数组设置最大值和最小值才可以mock。


另外测试中还是觉得生成的这个类型不太友好，如下图：

![image](https://user-images.githubusercontent.com/22909744/58488576-2f4d7f00-819c-11e9-89d8-91f50c73889e.png)

mock后的数据如下：

![image](https://user-images.githubusercontent.com/22909744/58488643-4be9b700-819c-11e9-987a-f02182a28912.png)

String 应该是小写的 s ，Integer应为小写的 i ，可否在生成的过程中进行转换？

ps：可以贴一下捐赠二维码

**Comment by qbb-dev** [comment]
好的，mock 问题的话请在yapi 中提issue,
String 应该是小写的 s ，Integer应为小写的 i  这个问题 应该不影响其他功能，只是为了和java 统一，如果有其他更好的理由请说明

**Comment by qbb-dev** [comment]
暂不考虑捐赠，如果觉得好用，请帮忙推广推广给个star，谢谢
