### ISSUE TITLE
参数缺失 false

### ISSUE THREAD

**Issue by ydcun** [diwand/YapiIdeaUploadPlugin#12]
## 版本号
~ 1.6.8

## 什么问题
~ 参数缺失
![image](https://user-images.githubusercontent.com/4220967/58694547-cfd2b780-83c5-11e9-9fcf-79ade139f2d5.png)

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
  2019.1.3

**Comment by qbb-dev** [comment]
下一个版本解决：1.6.9
