### ISSUE TITLE
@DeleteMapping注解的接口不能发布到yapi上

### ISSUE THREAD

**Issue by aqiu202** [diwand/YapiIdeaUploadPlugin#15]
## 版本号
~1.6.8
## 什么问题
~@DeleteMapping注解的接口不能发布到yapi上
## 如何复现此问题
~@DeleteMapping注解的接口不能发布到yapi上，改成~@RequestMapping(method=RequestMethod.DELETE,...)就可以
## 接口定义 (如果可以的话,请上传请求对象和响应对象)
![20190611145604](https://user-images.githubusercontent.com/24487480/59250325-869e2580-8c59-11e9-8f0c-cd7f429427bd.jpg)
![image](https://user-images.githubusercontent.com/24487480/59250191-20190780-8c59-11e9-901c-31f3d792a7a4.png)
## idea 版本
~2019.1

**Comment by aqiu202** [comment]
已经找到问题，@DeleteMapping和@PatchMapping的注解的路径配置错了，请自查

**Comment by qbb-dev** [comment]
好的

**Comment by aqiu202** [comment]
另外response一直没有数据，有报错
![image](https://user-images.githubusercontent.com/24487480/59338969-e669fe80-8d35-11e9-990f-f78528fae05b.png)

**Comment by qbb-dev** [comment]
> 另外response一直没有数据，有报错
> ![image](https://user-images.githubusercontent.com/24487480/59338969-e669fe80-8d35-11e9-990f-f78528fae05b.png)

这个报错是 你开启了java 类上传，没有找到 rt-sources jar，应该是有某个特殊的类型

**Comment by qbb-dev** [comment]
> > 另外response一直没有数据，有报错
> > ![image](https://user-images.githubusercontent.com/24487480/59338969-e669fe80-8d35-11e9-990f-f78528fae05b.png)
> 
> 这个报错是 你开启了java 类上传，没有找到 rt-sources jar，应该是有某个特殊的类型

可以提供下JsonResult 定义吗

**Comment by aqiu202** [comment]
> > > 另外response一直没有数据，有报错
> > > ![image](https://user-images.githubusercontent.com/24487480/59338969-e669fe80-8d35-11e9-990f-f78528fae05b.png)
> > 
> > 
> > 这个报错是 你开启了java 类上传，没有找到 rt-sources jar，应该是有某个特殊的类型
> 
> 可以提供下JsonResult 定义吗

JsonResult继承了HashMap，是不是不支持map序列化
![image](https://user-images.githubusercontent.com/24487480/59347889-52edf900-8d48-11e9-92c8-117b30fc7e09.png)

**Comment by qbb-dev** [comment]
之前的确没有考虑这个场景，后续版本考虑支持
