### ISSUE TITLE
GET请求封装对象参数问题

### ISSUE THREAD

**Issue by 820229268** [diwand/YapiIdeaUploadPlugin#16]
## 版本号
v1.6.8

## 什么问题
GET请求时  参数使用封装对象不能导入接口文档

## 如何复现此问题
        /**
	 * 获取用户分页列表
	 * @param param {@link UserAo}
	 * @return
	 */
	@GetMapping("/user")
	public ResponseAo<PageInfo<UserVo>> pageData(@RequestParam UserAo param){
		log.info("==> API: 获取用户分页列表");
		return ResponseAo.success(userService.findPage(param));
	}

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本

~

**Comment by qbb-dev** [comment]
暂不支持这样的写法，或请使用@RequestBody
