### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by dai794251336** [diwand/YapiIdeaUploadPlugin#17]
## 版本号
~ 
1.6.8

## 什么问题
~
![image](https://user-images.githubusercontent.com/26127871/59574185-e2006580-90e8-11e9-97aa-897a1f5054fb.png)

## 如何复现此问题
~ 
由于使用的是jiaoyu教育版激活方式，右击上传，直接报空指针异常。
于是在另外一个版本上测试，非教育版，采用破解方式激活的IDEA，没有报错。一切正常！

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
![image](https://user-images.githubusercontent.com/26127871/59574145-bf6e4c80-90e8-11e9-87d9-7017b25ef126.png)

**Comment by dai794251336** [comment]
原因：
![image](https://user-images.githubusercontent.com/26127871/59580341-5cd67a00-9103-11e9-94a5-16f51fffae57.png)
此处+号导致上传接口失败。

**Comment by qbb-dev** [comment]
暂不支持该种写法（此写法并不推荐）

**Comment by dai794251336** [comment]
了解

**Comment by Ridup** [comment]
mark

**Comment by Ridup** [comment]
> 暂不支持该种写法（此写法并不推荐）

我支持了这种写法  (￣▽￣)~*
