### ISSUE TITLE
model 属性 注释 支持 // 

### ISSUE THREAD

**Issue by sunlad1** [diwand/YapiIdeaUploadPlugin#18]
## 版本号
~ 

## 什么问题
model 属性 注释 支持 // 
对于成员变量我一般用// 进行注释。如果成员变量页用/** */进行注释的话代码可读性会比较差
纯属个人看法

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~

**Comment by qbb-dev** [comment]
由于该种写法并不符合java doc 的要求，暂不支持
