### ISSUE TITLE
上传提示 找不到rt-sources.jar，但是上传成功

### ISSUE THREAD

**Issue by dale19900108** [diwand/YapiIdeaUploadPlugin#19]
## 版本号
~ jdk 1.8.0-172
yapiUpload-1.6.8
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
JRE: 11.0.2+9-b159.60 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

## 什么问题
~上传提示 can not find sources java:/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre/lib/rt-sources.jar
但是接口上传成功

**Comment by qbb-dev** [comment]
这个是因为配置了 attachUploadUrl, 是找不到 源码包造成的，不影响
