### ISSUE TITLE
希望能改进以下几个问题

### ISSUE THREAD

**Issue by Wilson-He** [diwand/YapiIdeaUploadPlugin#2]
1.方法上的@XxxMapping没有设置value默认使用Controller的映射时上传报upload api error cause，希望能改成默认使用Controller的api地址，以下为报错方法例子：
@PostMapping
 public BaseResponse insert(@Validated(InsertGroup.class) @RequestBody BusinessInfoVO vo)
2.一些接口里必须请求参数上传到yapi后无法标志“是否必须"tag为是，建议可以读下JSR的校验注解，再根据注解中的group判定是否必传(个人业务场景可能出现一个VO增改通用，根据group确定是否必传，这个可能有点复杂)
@NotNull(groups = UpdateGroup.class)
@Null(groups = InsertGroup.class)
private Long id;
3.备注中含小于号"<"时会自动忽略至下一大于号，如“BaseResponse<List<BusinessInfo>>”上传到yapi成了BaseResponse>，站在前后端分离的角度个人认为可以忽略备注上传这一项，因为前端无需关注我们的方法是如何定义的，只需关注url、参数与返回值

**Comment by qbb-dev** [comment]
谢谢反馈，
第一个问题：这个场景的确没有考虑，1.6.6 改进
第二个问题：目前只支持 @NotNull ,暂不支持 分组和其他注解，后期考虑支持
第三个问题：考虑1.6.6 改进

**Comment by qbb-dev** [comment]
1.6.6 已发布
