### ISSUE TITLE
menu删除后不会重新生成

### ISSUE THREAD

**Issue by LBJWt** [diwand/YapiIdeaUploadPlugin#20]
## 版本号
~ 1.6.9

## 什么问题
~ 管理后台删除分类，上传删除分类的名称，不会重新新建分类

## 如何复现此问题
~  比如 
`/**
 *@description: 测试控制器
 *@menu test
 */ `
先upload这个test，然后删除这个分类，在重新upload，不会生产这个test分类
## 接口定义 (如果可以的话,请上传请求对象和响应对象)
~ 

## idea 版本
2019.1.3

**Comment by qbb-dev** [comment]
设计如此:需要重启idea,请看FAQ
