### ISSUE TITLE
支持入参对象内成员变量@NotNull/@NotEmpty注解

### ISSUE THREAD

**Issue by sunlad1** [diwand/YapiIdeaUploadPlugin#22]
支持入参对象内成员变量@NotNull/@NotEmpty注解，如下图
![image](https://user-images.githubusercontent.com/27797771/62033656-02aaf780-b21f-11e9-957a-f68226712c48.png)
![image](https://user-images.githubusercontent.com/27797771/62033680-0d658c80-b21f-11e9-88d1-75fcdd907524.png)
我们notnull的注解是写在入参对象的成员变量上的。
最好是支持//的注解方式。

**Comment by qbb-dev** [comment]
1.7.1 版本已支持
