### ISSUE TITLE
文件上传接口生成文旦异常

### ISSUE THREAD

**Issue by w420372197** [diwand/YapiIdeaUploadPlugin#24]
## 版本号
1.7.0
## 什么问题
文件上传接口生成文旦异常

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
定义一个 public RestResult importExcel(@RequestParam("file") MultipartFile[] file),生成文档是报 Convert to JSON failed. 
~ 

## idea 版本
IntelliJ IDEA 2017.2
Build #IU-172.3317.76, built on July 15, 2017
Licensed to Administrator

JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by qbb-dev** [comment]
暂不支持文件类型
