### ISSUE TITLE
dubbo接口上传信息不全

### ISSUE THREAD

**Issue by YoooLong** [diwand/YapiIdeaUploadPlugin#25]
## 版本号
~ 1.7.2

## 什么问题
~上次dubbo接口，参数的备注没有上传

## 如何复现此问题
~ 随便测试一个dubbo接口即可

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
~ 第一种： Msg getOrder(String username, String orderId);
 这种情况下，上传的body内容中没有具体的参数名称，如下
[
  {
    "java.lang.String": "String"
  },
  {
    "java.lang.String": "String"
  }
]
第二种：Msg getOrder(UserInfo info);
UserInfo 具体信息为：
public class UserInfo {
 /**
   *用户姓名
  */
String username; 
 /**
   *订单编号
  */
String orderId;

/*** get  set  忽略***/
}

这种情况下， 上传的body内容中没有具体的参数注释
[
  {
    "com.dubbo.req.GetOrderReq": {
      "username": "String",
      "orderId": "String"
    }
  }
]

## idea 版本
2019.1.4

**Comment by qbb-dev** [comment]
dubbo 是没有注释，这个暂时没有做，后面考虑做，主要先yapi 不支持dubbo,json 格式目前仅满足我们的需求
