### ISSUE TITLE
未知问题

### ISSUE THREAD

**Issue by QiangFangcn** [diwand/YapiIdeaUploadPlugin#26]
## 版本号
~ 
最新版
## 什么问题
~
sorry ,upload api error cause:请求参数 data 应当有必需属性 catid
## 如何复现此问题
~ 
sorry ,upload api error cause:请求参数 data 应当有必需属性 catid
## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
201801

**Comment by qbb-dev** [comment]
请问yapi 版本是多少

**Comment by QiangFangcn** [comment]
刚看了，1.41，好像这个只支持到1.50，所以我不能用

**Comment by qbb-dev** [comment]
你试下 1.7.0 版本
