### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by xiaour** [diwand/YapiIdeaUploadPlugin#27]
## V1.7.2
~ 

## 生成的接口模板在yapi系统删除后，此类无法再次生成
~

## 在yapi系统里删除已生成的接口，然后再次全类生成，此ID应该不存在了，可是提交上去的任然是此ID
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~

**Comment by qbb-dev** [comment]
应该是你删除了对应的菜单，请重启idea 就好，或者升级到1.7.3
