### ISSUE TITLE
sorry ,upload api error cause:请求参数 data 应当有必需属性 catid

### ISSUE THREAD

**Issue by ac3than** [diwand/YapiIdeaUploadPlugin#28]
## 版本号
~ 
yapiideauploadplugin1.7.3
## 什么问题
~
sorry ,upload api error cause:请求参数 data 应当有必需属性 catid
## 如何复现此问题
~ 选中方法 alt + u

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
@RequestMapping("add")
ApiResult add( RoleBo roleBo) {}
~ 

## idea 版本
2019.2
![QQ截图20190828184817](https://user-images.githubusercontent.com/13286382/63849340-7712bb00-c9c4-11e9-8e1c-c02d0c94356f.png)
![QQ截图20190828184829](https://user-images.githubusercontent.com/13286382/63849342-77ab5180-c9c4-11e9-928c-9a794a24fd3f.png)

yapi 的版本是  1.4.4

**Comment by ac3than** [comment]
只是普通的 springboot项目, 然后编辑 .idea/misc.xml 加入到 project 标签下, 重启 idea,重装 yapi插件都无效
```
    <component name="yapi">
        <option name="projectToken">xxx8da7fc2dd1c2xxx</option>
        <option name="projectId">61</option>
        <option name="yapiUrl">http://39.106.8.xx:xx00</option>
        <option name="projectType">api</option>
        <option name="attachUploadUrl">http://localhost/fileupload</option>
    </component>
```

**Comment by qbb-dev** [comment]
本插件从1.5 开始完全支持，

**Comment by qbb-dev** [comment]
之前默认支持1.5 以后的yapi 版本，请切换到v1.7.4 分支下，然后打开disk 找到1.7.4 重装，再试试，如果需要，请加入群644642474 @ernest 然后配合下对低版本兼容,谢谢

**Comment by ac3than** [comment]
> 之前默认支持 1.5 以后的 yapi 版本, 请切换到 v1.7.4 分支下, 然后打开 disk 找到 1.7.4 重装, 再试试, 如果需要, 请加入群 644642474 @ernest 然后配合下对低版本兼容, 谢谢

作者你好, 我刚刚升级 yapi 到 1.8.3, 但是上传还是提示 sorry ,upload api error cause:请求参数 data 应当有必需属性 catid
![QQ截图20190829090133](https://user-images.githubusercontent.com/13286382/63902324-a6184380-ca3b-11e9-8705-d43e34142b2f.png)
已经好了, 刚刚是升级后 token 自动刷新了, 我重新配置了 token 就好了, 谢谢
