### ISSUE TITLE
怎么添加tag标签 和@menu标签的多级分类

### ISSUE THREAD

**Issue by ciweigg2** [diwand/YapiIdeaUploadPlugin#29]
## 版本号
~ 
1.8.3

## 什么问题
~
注释怎么添加tag标签
怎么使用@menu多级分类 貌似class上面添加注解和method上面添加注解后不是class/method这样的分类目录显示在yapi的，

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2019.2

**Comment by qbb-dev** [comment]
多级分类需要 yapi 是 crazy 分支才能支持，tag 标签暂未支持
