### ISSUE TITLE
返回值的生成有问题

### ISSUE THREAD

**Issue by Nayacco** [diwand/YapiIdeaUploadPlugin#3]
## 版本号
~ 1.6.6

## 什么问题
~返回值生成有问题

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
controller
![image](https://user-images.githubusercontent.com/22909744/58301122-c7074200-7e17-11e9-937c-f043623931e4.png)

resultData返回类
![image](https://user-images.githubusercontent.com/22909744/58301058-9921fd80-7e17-11e9-89d6-b807ac9ecb3b.png)

生成的返回值没有HotlineSessionDetailVO对应的属性
![image](https://user-images.githubusercontent.com/22909744/58301142-df775c80-7e17-11e9-896b-250348501a7a.png)

~ 

## idea 版本
2018.2.4

**Comment by qbb-dev** [comment]
暂不支持E 定义，目前支持T 定义，下个版本加入

**Comment by Nayacco** [comment]
👍

**Comment by qbb-dev** [comment]
已发布1.6.7 支持多种泛型写法，支持PathVariable
