### ISSUE TITLE
支持map返回吗

### ISSUE THREAD

**Issue by ciweigg2** [diwand/YapiIdeaUploadPlugin#30]
## 版本号
~ 

## 什么问题
~
支持解析map返回吗，如果支持怎么用 我看其他issues有提到过对象支持// 这个怎么结合notnull使用
## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~

**Comment by qbb-dev** [comment]
1.7.5 支持，但是不建议map 返回
