### ISSUE TITLE
sorry ,upload api error cause:请求参数 data 应当有必需属性 catid

### ISSUE THREAD

**Issue by wuyingdu** [diwand/YapiIdeaUploadPlugin#39]
## 版本号
~ 
1.7.4
## 什么问题
~
上传接口提示必须配置必需属性 catid
## 如何复现此问题
~ 
在接口名上alt+u上传接口时提示的
![image](https://user-images.githubusercontent.com/45226442/65757302-7303c580-e149-11e9-80ed-b951b3d1fd16.png)
![image](https://user-images.githubusercontent.com/45226442/65757336-83b43b80-e149-11e9-86c5-fac6b1cb331c.png)

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2018.1.5

请问，在哪配置catid? 普通的api接口，非dubbo接口。

**Comment by qbb-dev** [comment]
yapi 版本太低需要不低于1.5
