### ISSUE TITLE
入参的生成有问题

### ISSUE THREAD

**Issue by Nayacco** [diwand/YapiIdeaUploadPlugin#4]
## 版本号
~ 1.6.6

## 什么问题
~入参的生成有问题

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
![image](https://user-images.githubusercontent.com/22909744/58301824-a987a780-7e1a-11e9-810a-202ac68bea27.png)

![image](https://user-images.githubusercontent.com/22909744/58301844-bb694a80-7e1a-11e9-9848-587183e8594e.png)

~ 

## idea 版本
2018.2.4

**Comment by qbb-dev** [comment]
下一版本支持 @PathVariable

**Comment by qbb-dev** [comment]
已发布1.6.7 支持多种泛型写法，支持PathVariable
