### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by dale19900108** [diwand/YapiIdeaUploadPlugin#40]
## 版本号
~ 1.7.4
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

## 什么问题
~空指针

## 如何复现此问题
~ 上传接口时出现。

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
`/**
     * 功能:   增加用户反馈.
     * <p>
     * 需要的参数和参数含义
     * <p>
     * userno    用户编号
     * content   反馈内容
     * image1    图片1的地址
     * image2    图片2的地址
     * image3    图片3的地址
     * contact   联系方式
     */
    @RequestMapping("/feedback")
    public ResponseData create(@RequestBody String body) {
        ResponseData rd = new ResponseData(ErrorCode.SUCCESS);
        try {

            // 转成json
            JSONObject param = JSONObject.parseObject(body);
            String userno = param.getString(RequestKey.USER_NO);
            String content = param.getString(RequestKey.CONTENT);
            String image1 = param.getString(RequestKey.IMAGE1);
            String image2 = param.getString(RequestKey.IMAGE2);
            String image3 = param.getString(RequestKey.IMAGE3);
            String contact = param.getString(RequestKey.CONTACT);

            rd = systemService.feedback(userno, content, image1, image2, image3, contact);

        }  catch (Exception e) {
            rd.setErrorCode(ErrorCode.FAIL.value());
            log.error(" list 异常", e);
        }
        return rd;
    }`
~

**Comment by qbb-dev** [comment]
加qq 群644642474  @Ernest
