### ISSUE TITLE
通过路径获得接口是否存在

### ISSUE THREAD

**Issue by chenglitao521** [diwand/YapiIdeaUploadPlugin#41]
## 版本号
~ 
yapi  1.8.3
插件  1.7.2
## 什么问题
~
代码中/api/interface/getbypath接口的调用，yapi貌似没有提供该接口？还是我版本太低
## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2019.2

**Comment by qbb-dev** [comment]
该接口只有crazy 分支存在，官方版本不存在，
