### ISSUE TITLE
返回数据异常

### ISSUE THREAD

**Issue by GaryLew** [diwand/YapiIdeaUploadPlugin#42]
## 版本号
~ V1.7.4

## 什么问题
~无法返回正确的数据

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

package com.feeling.msp.service.customer.controller;

import com.alibaba.fastjson.JSONObject;
import com.feeling.msp.service.base.service.IQueryService;
import com.feeling.msp.service.customer.form.LoginForm;

import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.util.Map;

@RestController
public class LoginController {
    @Resource(name = "loginService")
    IQueryService loginService;

    /**
     * @description: 登录
     * @param: [LoginForm]
     * @menu: 公共接口
     * @return: jsonObject
     * @date: 2019/09/11
     */
    @RequestMapping(value = "/Login",method = RequestMethod.POST)
    public JSONObject login(@Valid @RequestBody LoginForm loginRequest, HttpServletRequest request){
        Map<String,?> map = loginService.handle(request,loginRequest);
        JSONObject jsonObject = new JSONObject();
        jsonObject.putAll(map);
        return jsonObject;
    }

}

~ 

## idea 版本
2019.2

**Comment by qbb-dev** [comment]
不支持JSONObject，不能根据上下文确定里面到底是什么类型
