### ISSUE TITLE
orry ,upload api error cause:com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by xlzuijia** [diwand/YapiIdeaUploadPlugin#44]
## 版本号
~ 1.7.4

## 什么问题
~alt+u 报错

## 如何复现此问题
~ 配置单模块component

  <component name="yapi">
    <option name="projectToken">5908fe402ccaf4d26cf08002cfa****7f7332240f6ebd2b278e668a9f2</option>
    <option name="projectId">38</option>
    <option name="yapiUrl">http://114.55.*.*:3000</option>
    <option name="projectType">api</option>
    <option name="attachUploadUrl"></option>
    <option name="returnClass"></option>
  </component>

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2018.2.1

**Comment by qbb-dev** [comment]
你好，请不要暴露自己的ip 哦，该ip 也访问不通，初步判断这个问题为请求你的yapi 出现异常，如果未能解决请加群644642474 然后@ernest

**Comment by monsterLM** [comment]
怎么解决的？
