### ISSUE TITLE
idea 上传出错get config error:1

### ISSUE THREAD

**Issue by lferic** [diwand/YapiIdeaUploadPlugin#45]
## 版本号
Version: 1.7.4

## 什么问题
上传报错：get config error:1

## 如何复现此问题
alt+u 快捷键

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
misc.xml配置
 <component name="yapi">
        <option name="moduleList">moduleName1</option>
    </component>
    <component name="moduleName1">
        <option name="moduleName1.projectToken">f50caefa125eb0f5bdd666b4cfdbc37c46a78984f9651e41c28260ac3b748046</option>
        <option name="moduleName1.projectId">18</option>
        <option name="moduleName1.yapiUrl">http://10.200.172.214:3000</option>
        <option name="moduleName1.projectType">api</option>
        <option name="moduleName1.returnClass">.Resul</option>
    </component>
  <component name="FrameworkDetectionExcludesConfiguration">
    <file type="web" url="file://$PROJECT_DIR$/teacher-web" />
  </component>

## idea 版本
2017.1.2

**Comment by qbb-dev** [comment]
moduleName1 是项目名

**Comment by lferic** [comment]
现在点击导入又提示concert to son failed
