### ISSUE TITLE
idea 上传出错sorry ,upload api error cause:path第一位必需为 /, 只允许由 字母数字-/_:.! 组成

### ISSUE THREAD

**Issue by lferic** [diwand/YapiIdeaUploadPlugin#47]
## 版本号
~ 
1.7.4
## 什么问题
~
点击上传报 sorry ,upload api error cause:path第一位必需为 /, 只允许由 字母数字-/_:.! 组成
## 如何复现此问题
~ 
点击上传
## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2017.1.2

**Comment by lferic** [comment]
补充：/**
	 * 测试RequestHeader desc 规范的多个
	 * @param uid 用户id
	 * @param bid baby id
	 * @param request
	 * @param response
	 */
	@RequestMapping(value = "/testRequestDesc4")
	public void testRequestDesc4(@RequestHeader(name = "uid")Integer uid, @RequestParam(name = "bid")Integer bid, HttpServletRequest request, HttpServletResponse response){

	}
用的这个测试接口上传报的错误

**Comment by qbb-dev** [comment]
是否类上面的路径没有  /

**Comment by lferic** [comment]
是没加，感谢
