### ISSUE TITLE
无法根据返回类型获取属性值的情况

### ISSUE THREAD

**Issue by Nayacco** [diwand/YapiIdeaUploadPlugin#5]
## 版本号
~ 1.6.6

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

在这种情况下，无法根据ResponseEntity获取到属性值，从而生成接口，是否考虑：在有注释的情况下，以注释为主？

![image](https://user-images.githubusercontent.com/22909744/58302471-d4272f80-7e1d-11e9-9438-0f9a4726ebf2.png)

~

**Comment by qbb-dev** [comment]
暂不考虑通过注释生成，并不是所有的人的注释是规范，这种情况建议规范返回值 书写
