### ISSUE TITLE
1.7.4+版本报错

### ISSUE THREAD

**Issue by swuzjb** [diwand/YapiIdeaUploadPlugin#51]
## 版本号
~ 
1.7.4+
## 什么问题
~
上传时提示配置错误
get config error:Index 1 out of bounds for length 1
## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019
Licensed to Gu Xinyan
Subscription is active until October 29, 2020
For educational use only.
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: 
Non-Bundled Plugins: Lombook Plugin, YapiUpload, cn.yiiguxing.plugin.translate, com.alibaba.p3c.smartfox, mobi.hsz.idea.gitignore, com.kukido.eclipser, BashSupport, MavenRunHelper, edu.umontreal.hatchery

**Comment by gofreehj** [comment]
同样的错误

**Comment by qbb-dev** [comment]
是否能贴下配置文件

**Comment by dale19900108** [comment]
同样报错。
后来找到了问题，是这个配置引起的。去掉了就好了
      <option name="returnClass">com.project.Response</option>

**Comment by dale19900108** [comment]
@gofreehj @swuzjb

**Comment by swuzjb** [comment]
我这里去调也不行。。
配置文件如下 1.7.3 是可以的
```
  <component name="yapi">
    <option name="moduleList">academy-hom,academy-portal</option>
  </component>
  <component name="academy-hom">
    <option name="academy-hom.Token">19bc6ce960553c882f79167fa94ae77a</option>
    <option name="academy-hom.Id">12</option>
    <option name="academy-hom.Url">http://b.com</option>
    <option name="academy-hom.Type">api</option>
  </component>
  <component name="academy-portal">
    <option name="academy-portal.Token">9bf6989fabb8e69f82c348ff0d455741</option>
    <option name="academy-portal.Id">14</option>
    <option name="academy-portal.Url">http://a.com</option>
    <option name="academy-portal.Type">api</option>
  </component>
```

**Comment by qbb-dev** [comment]
> 我这里去调也不行。。
> 配置文件如下 1.7.3 是可以的
> 
> ```
>   <component name="yapi">
>     <option name="moduleList">academy-hom,academy-portal</option>
>   </component>
>   <component name="academy-hom">
>     <option name="academy-hom.Token">19bc6ce960553c882f79167fa94ae77a</option>
>     <option name="academy-hom.Id">12</option>
>     <option name="academy-hom.Url">http://b.com</option>
>     <option name="academy-hom.Type">api</option>
>   </component>
>   <component name="academy-portal">
>     <option name="academy-portal.Token">9bf6989fabb8e69f82c348ff0d455741</option>
>     <option name="academy-portal.Id">14</option>
>     <option name="academy-portal.Url">http://a.com</option>
>     <option name="academy-portal.Type">api</option>
>   </component>
> ```
1.7.4 以后修改了配置名称，请看下文档

**Comment by swuzjb** [comment]
看到了。。。这里太隐晦了，建议高亮一下。。。
