### ISSUE TITLE
idea 一键上传接口到yapi插件使用报错（服务器出错）

### ISSUE THREAD

**Issue by yyy-charlie** [diwand/YapiIdeaUploadPlugin#52]
## 版本号
~ YapiUpload v1.7.4

## 什么问题
~idea上传接口到yapi时报错：sorry ,upload api error cause:服务器出错...

## 如何复现此问题
~ 1、在idea安装YapiUpload 插件并重启idea
2、在.idea 文件夹下的misc.xml 中配置信息
3、选中controller 类中的方法名称或类名，右击YapiUpload(alt+u快捷键)
4、idea提示：sorry ,upload api error cause:服务器出错...

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2019.1

**Comment by qbb-dev** [comment]
请加群qq644642474 @ernest

**Comment by kkxYQ** [comment]
我的情况跟他一摸一样，请问如何解决的呢
