### ISSUE TITLE
返回值为泛型错误

### ISSUE THREAD

**Issue by songjhh** [diwand/YapiIdeaUploadPlugin#55]
## 版本号
1.7.6

## 什么问题
返回值为泛型，接口无法解析里面的对象

## 如何复现此问题
```
    /**
     * 获取客户详情
     *
     * @param id 客户的id
     * @return
     */
    @GetMapping("/{id}")
    public DataResponse<CustomerVo> get(@PathVariable String id) {
        return new DataResponse<>(ResponseCode.SUCCESS, customerService.getById(id));
    }
```

名称 | 类型 | 是否必须 | 默认值 | 备注 | 其他信息
-- | -- | -- | -- | -- | --
data | object | 非必须 |   | D | 备注: D
code | int | 非必须 |   |   | mock: @integer
message | String | 非必须 |   |   | mock: @string

无法展开CustomerVo对象，其中data就是泛型字段

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

如上

## idea 版本
2019.02.04专业版

**Comment by qbb-dev** [comment]
目前支持 T,E,A,B,K,V
