### ISSUE TITLE
please check config,[projectToken,projectId,yapiUrl,projectType]

### ISSUE THREAD

**Issue by astali** [diwand/YapiIdeaUploadPlugin#56]
## 版本号
~ 1.7.6

## 什么问题
~please check config,[projectToken,projectId,yapiUrl,projectType]

## 如何复现此问题
~ 
<component name="yapi">
        <option name="moduleList">moduleName1,moduleName2</option>
    </component>

    <component name="moduleName1">
        <option name="moduleName1.projectToken">aaax1</option>
        <option name="moduleName1.projectId">16</option>
        <option name="moduleName1.yapiUrl">https://xxx.com</option>
        <option name="moduleName1.projectType">api</option>
    </component>

    <component name="moduleName2">
        <option name="moduleName2.projectToken">xxxx2</option>
        <option name="moduleName2.projectId">20</option>
        <option name="moduleName2.yapiUrl">https://xxx.com</option>
        <option name="moduleName2.projectType">api</option>
    </component>

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~

**Comment by qbb-dev** [comment]
1.7.4 以上配置名称换了，请看文档

**Comment by chenglongzjg** [comment]
> 1.7.4 以上配置名称换了，请看文档

文档中1.7.4之后的配置不就是他这个配置么？
