### ISSUE TITLE
可以生成mock吗

### ISSUE THREAD

**Issue by JacBian** [diwand/YapiIdeaUploadPlugin#58]
## 版本号
~ 

## 什么问题
~

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~

**Comment by JacBian** [comment]
我看到1.7.6支持
support base mock power 
但是没有示例

**Comment by qbb-dev** [comment]
> 我看到1.7.6支持
> support base mock power
> 但是没有示例

自动根据类型选择mock 类型
