### ISSUE TITLE
请求参数丢失

### ISSUE THREAD

**Issue by Nayacco** [diwand/YapiIdeaUploadPlugin#6]
## 版本号
~ 1.6.7

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
![image](https://user-images.githubusercontent.com/22909744/58367898-9ad2ea80-7f17-11e9-8318-4cf03428cb32.png)
![image](https://user-images.githubusercontent.com/22909744/58367917-c3f37b00-7f17-11e9-8dec-e692ccf0202b.png)

没有生成请求参数
~ 

## idea 版本
2018.2.4

**Comment by vinsoncho** [comment]
这个接口好像并不规范，用postman测试了一下，get请求发送格式为formData时，controller参数序列化时失败，如下图：
![image](https://user-images.githubusercontent.com/22909744/58392497-dcc17500-806c-11e9-89ef-578febe9c300.png)

如果get请求发送格式为application/json时，可以成功，如下图：
![image](https://user-images.githubusercontent.com/22909744/58392541-037fab80-806d-11e9-8719-2213f1362dd0.png)

但是yapi中，如果是get请求，并不能添加json格式的请求数据

**Comment by qbb-dev** [comment]
1.6.8 支持多个 不带注解参数接收的接口
