### ISSUE TITLE
controller类上RequestMapping 中常量无法解析

### ISSUE THREAD

**Issue by GeekDaniel** [diwand/YapiIdeaUploadPlugin#61]
## 版本号
~ 1.7.6

## 什么问题
~ RequestMapping 中常量无法解析

## 如何复现此问题
~ @RequestMapping(URL_PREFIX + "/user")
     public class UserController {
   ...
     }

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2018.1

**Comment by qbb-dev** [comment]
目前支持
@RequestMapping(URL_PREFIX)
public class UserController {
...
}

但是不支持
@RequestMapping(URL_PREFIX+”/user")
public class UserController {
...
}

不建议这么写，后面应该也不会支持该种写法
