### ISSUE TITLE
方法级别RequestMapping 注释value 为空无法解析

### ISSUE THREAD

**Issue by GeekDaniel** [diwand/YapiIdeaUploadPlugin#62]
## 版本号
~ 1.7.6

## 什么问题
~ 方法级别RequestMapping 注释value 为空无法解析

## 如何复现此问题
~ @RequestMapping(method = RequestMethod.GET)
   List<User> queryUsers(@RequestParam("status") int status){
   ...
   }

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2018.1

**Comment by qbb-dev** [comment]
下个版本处理
