### ISSUE TITLE
如果接口中出现多个url，插件会报空指针

### ISSUE THREAD

**Issue by panhainan** [diwand/YapiIdeaUploadPlugin#64]
## 版本号
1.7.6

## 什么问题
接口出现多个url，上传接口会报空指针异常

## 如何复现此问题
使用@RequestMapping(value = {"/a"})或者@RequestMapping(value = {"/a","/b"})这种形式标明方法或者类，然后点击上传，会报插件空指针异常

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2019.3

**Comment by qbb-dev** [comment]
目前不支持该写法，后面支持
