### ISSUE TITLE
1.7.7无法生成字段注释

### ISSUE THREAD

**Issue by ciweigg2** [diwand/YapiIdeaUploadPlugin#65]
## 版本号
~ 
1.7.7

## 什么问题
~
1.7.7无法生成字段注释

## 如何复现此问题
~ 
crazy_yapi版本 正常上传接口到yapi

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~

**Comment by qbb-dev** [comment]
1.7.8 修复，请在1.7.8 分支下载最新包
