### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by hangzhi7** [diwand/YapiIdeaUploadPlugin#66]
不好意思，之前提过这个问题，忘记跟踪了导致被您关闭类，上次上传的代码您说没有重现问题，这次就直接上图

## 版本号
~ 1.7.7

## 什么问题
~
[报错：2](https://s2.ax1x.com/2020/01/09/lRWaAP.jpg)

[报错：3](https://s2.ax1x.com/2020/01/09/lRWt0I.jpg)

[正常](https://s2.ax1x.com/2020/01/09/lRWN7t.jpg)

您提示错误的不友好，2，3都不知道是什么错误

**Comment by qbb-dev** [comment]
已经复现问题，和泛型冲突了， 请类名称定义不要用这几个字母
        genericList.add("T");
        genericList.add("E");
        genericList.add("A");
        genericList.add("B");
        genericList.add("K");
        genericList.add("V");
