### ISSUE TITLE
请求参数丢失2

### ISSUE THREAD

**Issue by Nayacco** [diwand/YapiIdeaUploadPlugin#7]
## 版本号
~ 1.6.7

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
![image](https://user-images.githubusercontent.com/22909744/58367975-9529d480-7f18-11e9-99c2-1f68737a24e2.png)

![image](https://user-images.githubusercontent.com/22909744/58367981-a4a91d80-7f18-11e9-9756-a01f3f75f3d5.png)

**Comment by qbb-dev** [comment]
@RequestParam 在query 中
