### ISSUE TITLE
多模块项目中，模块项目前缀相同提交接口会到其他项目

### ISSUE THREAD

**Issue by tangjiale** [diwand/YapiIdeaUploadPlugin#70]
## 版本号
~ 1.7.8

## 什么问题
~ 多模块项目中，模块项目前缀相同提交接口会到其他项目

## 如何复现此问题
~  多模块项目中两个项目命名为 test-in,test-into ,在moduleList 配置中 test-in 在test-into前面，提交项目test-into的代码会提交到test-in项目中

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~  在UploadToYapi.java 文件中， 代码67行 if (virtualFile.contains(moduleList[i])) { ，建议吧contains改为equals

## idea 版本
2019.3

**Comment by FurionCS** [comment]
谢谢反馈，下个版本解决
