### ISSUE TITLE
期望notnull在文档注释中使用，标识属性是否必填

### ISSUE THREAD

**Issue by bywei** [diwand/YapiIdeaUploadPlugin#72]
## 版本号
~ 1.7.8

## 什么问题
~ 期望notnull在文档注释中使用，标识属性是否必填。 在不使用@NotNull注解的情况下，直接使用文档注释能够识别属性是否必填

`    /**
     * 热门城市
     * @NotNull
     */
    private String hot;`

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2019.1.4

**Comment by qbb-dev** [comment]
@NotNull 可以用在字段上  /** * 热门城市 *  */ @NotNull private String hot;
