### ISSUE TITLE
返回值解析问题

### ISSUE THREAD

**Issue by swuzjb** [diwand/YapiIdeaUploadPlugin#8]
## 版本号
~ 
1.6.7
## 什么问题
~
包含多层次泛型类时 只能获取第一层泛型
## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
![image](https://user-images.githubusercontent.com/3627122/58393950-97ed0c80-8073-11e9-9f41-6e8fbe3d0583.png)
![image](https://user-images.githubusercontent.com/3627122/58393965-a6d3bf00-8073-11e9-9cbb-b7b15653366e.png)

~

**Comment by swuzjb** [comment]
不好意思哈，我再反馈一个问题，就是当一个分类在yapi上删除后，重新上传接口这个分类不会被重新创建

**Comment by qbb-dev** [comment]
删除了yapi这个分类，需要重启下idea ，做了一层本地缓存

**Comment by swuzjb** [comment]
> 删除了yapi这个分类，需要重启下idea ，做了一层本地缓存

好的 非常感谢。。那泛型类的问题后续版本有计划么？

**Comment by qbb-dev** [comment]
请提供下多层泛型的数据结构，原来是支持的

**Comment by qbb-dev** [comment]
下个版本1.6.8支持这种写法

**Comment by qbb-dev** [comment]
请更新到1.6.8  支持类上的path 引用，支持Response<List<User>> 写法

**Comment by swuzjb** [comment]
非常感谢。已更新。
