### ISSUE TITLE
idea 上传接口插件报错

### ISSUE THREAD

**Issue by coralandbill** [diwand/YapiIdeaUploadPlugin#89]
## 版本号
1.8.0

## 什么问题
上传报错
![image](https://user-images.githubusercontent.com/10264765/79548534-31783f00-80c8-11ea-982e-be17e873f54e.png)

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
![image](https://user-images.githubusercontent.com/10264765/79548522-2b825e00-80c8-11ea-8ab0-232fdaca48a2.png)

~ 

## idea 版本
IntelliJ IDEA 2018.3.6 (Ultimate Edition)
Build #IU-183.6156.11, built on March 25, 2019

JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4

**Comment by FurionCS** [comment]
yapi 版本需要1.5.x以上
