### ISSUE TITLE
接口路径配置了正则匹配的话，上传失败

### ISSUE THREAD

**Issue by yincu** [diwand/YapiIdeaUploadPlugin#90]
## 版本号
~ 
1.8.0
## 什么问题
~
报如下错误
AM	sorry ,upload api error cause:path第一位必需为 /, 只允许由 字母数字-/_:.! 组成

接口配置为：
 @RequestMapping(value = "/refresh/{id:^[0-9]\\d*$}", method = RequestMethod.POST)
## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2018.2

**Comment by FurionCS** [comment]
暂不支持
