### ISSUE TITLE
请求参数上包含 数组、List集合的时候将会上传失败

### ISSUE THREAD

**Issue by VincentCh01** [diwand/YapiIdeaUploadPlugin#92]
## 版本号
1.8.0

## 什么问题
请求参数上包含 数组、List集合的时候将会上传失败

## 如何复现此问题
写个测试接口，请求参数上包含 数组、List集合类，使用插件上传到Yapi将会失败

## 接口定义 (如果可以的话,请上传请求对象和响应对象)
String test(List<String> params);
String test(String[] params);

## idea 版本
2020.1

**Comment by FurionCS** [comment]
1.8.1 解决
