### ISSUE TITLE
上传接口覆盖问题

### ISSUE THREAD

**Issue by shihaoH** [diwand/YapiIdeaUploadPlugin#95]
## 版本号
~ 1.7.8

## 什么问题
~ 上传接口时如何做到不影响现有的接口，而非覆盖上传

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2019.3

**Comment by FurionCS** [comment]
目前只支持 备注非覆盖上传

**Comment by shihaoH** [comment]
> 目前只支持 备注非覆盖上传

什么备注
