### ISSUE TITLE
添加失败

### ISSUE THREAD

**Issue by wangdefeng** [diwand/YapiIdeaUploadPlugin#99]
## 版本号
~ 1.8.0

## 什么问题
~此种情况时会导致接口上传失败：
 @RequestMapping(value = {"/orgTeachers, /allStarMember"}, method = RequestMethod.POST)
![image](https://user-images.githubusercontent.com/7414117/82968793-b1b38d80-a000-11ea-8aff-0ab49fc33697.png)

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2020.1

**Comment by FurionCS** [comment]
不支持多个url 的情况
